language: node_js
node_js:
- '6'
- '5'
- '4'
script: npm run test:cov
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: hGWQG4XNGyJRizBbjIFynasTT8GSUE1Zcdh/45DSMdr2CRl4slhDZYXfY2DWBSCZ3rMc7gGZLu16UPYXX4HRHO1+BrEh45XZzz7peR1qmA0g1ROeah1WgsrY55gXCXixis1RQmI/YuQljXmFjM8p9nm1A7XGAoolNZaz4U/CGCVPq29ROCD8AhW0ZB1TIKe8y6fHMysArPOCKGD/fk6vh7T1RXQZ4GP5fxIX7+TxuUTFmzkS8PMTH/W9M0KXfUnugSj4+WQGLDl/SPEo58teQDPbbPc7CIBAy0wNjEUqo+4S9EMw90GVQFvVfdqUboIjZd7dbrZrlkq5tlzJEdCeh3vvwY3RNGcnLM/PjyBoDMJdxlu6V4gJ/CFzQONNkMZgWc398QWVGwKHa16MST/BkX6KtOGy50YOquruaRWBYDKAjFVapBTpQd35Y/0PL4hMGHgvbgDAuPJ67BCGZ7bnhWtJ9P7SRipW+/1XPWkb0ru9x345jVi6PDCW+UggM9n7DIsPmfQByaQMpCi5QaBhi/dhRxz5UBF8AaCP3zgmSbe1F8Rq4nOsrVXfemLHeiaXL2f0l5fh1d7YbkPWh2TeF/2xOnzZSWXsk9WpV896wBNtcevBqWqXde0UWsezJKmkUc3YMllIVgcZNHXUKHgNWCAN10SEcaaJjbiPo13Xo0M=
