version: '2'
services:
  lint:
    build: .
    command: npm run lint
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
  test:
    build: .
    command: npm run test
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
